# Generated by Django 3.0.2 on 2020-02-10 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_parser', '0002_auto_20200210_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 23, 6, 2, 832212)),
            preserve_default=False,
        ),
    ]
